# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: react app deployment with surge

on:
  push:
    branches: [ master ]
 

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: installing all dependencies with npm install
    - run: npm install 
    - name: build react app
    - run: npm run build
    - name: installing surge
    - run: npm install --global surge
    - name: deploying  build with surge   
    - run: surge ./build my-reactapp.surge.sh  --token ${{secrets.REACT_TOKEN}}
       
